### PR TITLE
Button to scroll to next root level comment

### PR DESCRIPTION
**Pull request by ejbills**
- Adds a button (arrowshape.bounce.right.fill) to the floating pill that scrolls to the next root level comment.
- The "next comment" is picked by selecting the next comment after the comment currently at a line 35% from the top of the screen.

### CODE REVIEW

**Comment by ojsef39** [comment]
[As of FR from Discord](https://discord.com/channels/1094807340903039048/1140331584122261604)

**Comment by ojsef39** [comment]
Hi, noticed that in some comments the skip button doesn't work for some reason.

 The first one works fine, and then the next one won't work, scroll around a bit and then it works again.

https://github.com/Kinark/winston/assets/43563019/d34f679e-e16a-4df9-a737-f675365efd60

**Comment by ojsef39** [comment]
also found this interesting bug on my iPad lmao

https://github.com/Kinark/winston/assets/43563019/7a1a9000-2106-4c40-aba7-6660de42ec12

**Comment by Kinark** [comment]
> Hi, noticed that in some comments the skip button doesn't work for some reason.
> 
> The first one works fine, and then the next one won't work, scroll around a bit and then it works again.
> 
>  CleanShot.2023-08-31.at.17.21.05.mp4

It seems pretty laggy in the video, does it feels the same in the real device? We need this feature to be as smooth as possible.

What usually causes lag on programatically scrolling is the change of states in between the scroll animation @ejbills, not sure if that's the case tho.

**Comment by ojsef39** [comment]
> It seems pretty laggy in the video, does it feels the same in the real device? We need this feature to be as smooth as possible.

Can only say for sure for my ipad, there it feels like in the video; on iphone i can't confirm for sure since i have a intel mac and im sure this can cause lags in my simulator lmao

I'll test in on my iphone when my apple developer enrolment goes trough, since i have an MDM installed on my phone and it doesn't allow installing untrusted apps 🤦🏽‍♂️

**Pull request merged**
